apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: restauranty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: sanasiddiqui115/restauranty-auth:IMAGE_TAG
          ports:
            - containerPort: 3001
          env:
            - name: SECRET
              value: "MySecret1!"
            - name: MONGODB_URI
              value: "mongodb://mongo:27017/resturanty"
            - name: CLOUD_NAME
              value: "dh0nbrf1g"
            - name: CLOUD_API_KEY
              value: "473375467426492"
            - name: CLOUD_API_SECRET
              value: "lmGPbD1o-swmE6IgTrOR0c1ZK9E"
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: restauranty
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: auth
