apiVersion: apps/v1
kind: Deployment
metadata:
  name: items
  namespace: restauranty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: items
  template:
    metadata:
      labels:
        app: items
    spec:
      containers:
        - name: items
          image: sanasiddiqui115/restauranty-items:latest
          ports:
            - containerPort: 3003
          env:
            - name: SECRET
              value: "MySecret1!"
            - name: MONGODB_URI
              value: "mongodb://mongo:27017/resturanty"
            - name: CLOUD_NAME
              value: "dh0nbrf1g"
            - name: CLOUD_API_KEY
              value: "473375467426492"
            - name: CLOUD_API_SECRET
              value: "lmGPbD1o-swmE6IgTrOR0c1ZK9E"
---
apiVersion: v1
kind: Service
metadata:
  name: items
  namespace: restauranty
spec:
  ports:
    - port: 3003
      targetPort: 3003
  selector:
    app: items
