apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: restauranty

resources:
  - namespace.yaml
  - mongo.yaml
  - auth-secrets.yaml
  - auth.yaml
  - discounts.yaml
  - items.yaml
  - frontend.yaml
  - ingress.yaml
